# Generated by Django 5.2.12 on 2026-04-03 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_inventoryentry_shift_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enable_addons',
            field=models.BooleanField(default=False, help_text='قائمة إضافات بأسعار (مثل جبن، بطاطس) تُزاد على سعر الصنف عند الطلب.', verbose_name='إضافات اختيارية'),
        ),
        migrations.AddField(
            model_name='category',
            name='enable_drink_options',
            field=models.BooleanField(default=False, help_text='عناوين جاهزة (بدون سكر، زيادة ثلج…) + نص حر؛ تظهر في الفاتورة والمطبخ والبار.', verbose_name='خيارات تفصيل المشروب'),
        ),
        migrations.AddField(
            model_name='category',
            name='enable_sizes',
            field=models.BooleanField(default=False, help_text='عند التفعيل يُعرّف لكل صنف أسعار لعدة أحجام بدل سعر واحد فقط.', verbose_name='أحجام للأصناف'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='drink_detail',
            field=models.TextField(blank=True, verbose_name='تفاصيل المشروب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='extras_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='إضافات وخيارات (JSON)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم الحجم (نسخة)'),
        ),
        migrations.AlterField(
            model_name='cashierprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliverydriver',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventoryentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر الأساسي'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='cash_in_drawer',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ما أدخله الكاشير عند إغلاق الشيفت بعد عدّ النقد.', max_digits=10, null=True, verbose_name='الدرج بعد العدّ'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='موجب = زيادة في الدرج، سالب = عجز عن المطابقة.', max_digits=10, null=True, verbose_name='الفرق (الدرج − المطابقة)'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='system_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مفروض المبيعات (طلبات) + واردات الشيفت؛ يُقارن بالدرج لحساب الزيادة أو العجز.', max_digits=10, null=True, verbose_name='مجموع المطابقة'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CategoryAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='pos.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'إضافة تصنيف',
                'verbose_name_plural': 'إضافات التصنيف',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DrinkOptionPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='النص')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink_presets', to='pos.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'خيار مشروب',
                'verbose_name_plural': 'خيارات المشروبات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='اسم الحجم')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='pos.menuitem', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'حجم صنف',
                'verbose_name_plural': 'أحجام الأصناف',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='pos.menuitemsize', verbose_name='الحجم'),
        ),
    ]
