# Generated by Django 5.2.12 on 2026-04-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_menu_sizes_addons_drink_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='orders_total_at_close',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='لقطة: طلبات مطبوعة + مكتملة ضمن الشيفت وقت العدّ.', max_digits=10, null=True, verbose_name='مجموع مبيعات الطلبات عند الإغلاق'),
        ),
        migrations.AddField(
            model_name='shift',
            name='revenue_booked',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='للتقارير: مبيعات الطلبات + زيادة الدرج إن وُجدت؛ عند العجز = المبيعات فقط.', max_digits=10, null=True, verbose_name='إيراد مسجّل'),
        ),
    ]
