# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_shift_revenue_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(
                blank=True,
                help_text='يُسجَّل عند الإلغاء بموافقة المدير؛ الطلب الملغي لا يُحسب في المبيعات.',
                verbose_name='سبب الإلغاء',
            ),
        ),
    ]
