# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_order_cancellation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_key', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='مفتاح الهاتف')),
                ('display_phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف المعروض')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='اسم العميل')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عميل ديليفري',
                'verbose_name_plural': 'عملاء الديليفري',
                'ordering': ['-updated_at'],
            },
        ),
    ]
