# Generated by Django 5.2.13 on 2026-04-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_orderactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderactivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
